apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake-smtp.fullname" . }}
  labels:
    {{- include "fake-smtp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fake-smtp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fake-smtp.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "gessnerfl/fake-smtp-server:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 5080
              protocol: TCP
            - name: smtp
              containerPort: 5025
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v3/api-docs
              port: web
          readinessProbe:
            httpGet:
              path: /v3/api-docs
              port: web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

