apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orders.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orders.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "orders.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OrdersService__ZipkinEndpoint
              valueFrom:
                configMapKeyRef:
                  name: zipkin
                  key: endpoint
            - name: OrdersService__ExposePrometheusMetrics
              value: {{ .Values.exposePrometheusMetrics | quote }}
            - name: OrdersService__IdentityServer__Authority
              valueFrom:
                configMapKeyRef:
                  name: authentication
                  key: authority
                  optional: true
          ports:
            - name: http-orders
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 20
            httpGet:
              path: /healthz/liveness
              port: http-orders
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 3
            httpGet:
              path: /healthz/readiness
              port: http-orders
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
